name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  release-drafter:
    uses: typisttech/.github/.github/workflows/release-drafter.yml@v2
    permissions:
      contents: write
      pull-requests: read
